---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: concourse-db
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:17.2
  instances: 1

  storage:
    storageClass: csi-rbd-sc
    size: 10G

  backup:
    barmanObjectStore:
      destinationPath: s3://concourse-backups/
      endpointURL: http://10.10.0.5:1080/
      s3Credentials:
        accessKeyId:
          name: rgw-backups
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: rgw-backups
          key: SECRET_ACCESS_KEY
    retentionPolicy: "30d"

  resources:
    requests:
      memory: "512Mi"
      cpu: "1"
    limits:
      memory: "1Gi"
      cpu: "2"
