---
apiVersion: v1
kind: Namespace
metadata:
  name: vault
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/helmrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: hashicorp
  namespace: default
spec:
  interval: 2h
  url: https://helm.releases.hashicorp.com
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
  namespace: default
spec:
  interval: 30m
  targetNamespace: vault
  chart:
    spec: 
      chart: vault
      version: "0.x"
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: default
  values:
    # yaml-language-server: $schema=https://raw.githubusercontent.com/hashicorp/vault-helm/refs/heads/main/values.schema.json
    injector:
      enabled: false
    server:
      auditStorage:
        enabled: true
      enabled: true
      ha:
        enabled: true
        replicas: 3
        raft:
          enabled: true
      ingress:
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
        enabled: true
        hosts:
          - host: vault.iad1.nic-a.net
      resources:
        requests:
          memory: 256Mi
          cpu: 250m
        limits:
          memory: 512Mi
          cpu: 1000m
      service:
        type: NodePort
      standalone:
        enabled: false
    ui:
      enabled: true
      serviceType: ClusterIP
