---
apiVersion: v1
kind: Namespace
metadata:
  name: ceph-csi-rbd
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/helmrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: ceph-csi
  namespace: ceph-csi-rbd
spec:
  interval: 2h
  url: https://ceph.github.io/csi-charts
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ceph-csi-rbd
  namespace: ceph-csi-rbd
spec:
  interval: 30m
  chart:
    spec:
      chart: ceph-csi-rbd
      version: "3.x"
      sourceRef:
        kind: HelmRepository
        name: ceph-csi
        namespace: ceph-csi-rbd
      interval: 2h
  values:
    provisioner:
      replicaCount: 1
      strategy:
        type: Recreate
        rollingUpdate: null
